### ISSUE TITLE
[Android] Ask user to upgrade to version 1.2.0

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-android#1170]
As soon as the WebInterface allows to upgrade the implmentation to version 1.2.0 we want to ask the user with a lower version to upgrade. 

- [ ] Safe Settings (Show upgrade available if version < 1.2.0)
- [ ] Safe settings (Show "Up to date" for  v1.2.0 )

**Comment by biafra23** [comment]
Depends on: https://app.zenhub.com/workspaces/safe-multisig---web-5ce554debb310a35b2f8b6f8/issues/gnosis/safe-react/1383

**Comment by DmitryBespalov** [comment]
too old
