### ISSUE TITLE
EIP-3770: Adjust receive screen 

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-android#1734]
- [ ] Show network prefix for safe address if enabled (as defined in #1731, #1732)
- [ ] Add link to network prefix settings screen

![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/b5a88aa3-e163-4e6c-a997-b3e43e2608e5)

**Comment by the-real-chrizzo** [comment]
Will be closed. New design will be proposed and implemented to take care of this.
