### ISSUE TITLE
Mini rebrand (new splash screen logo and new launcher icons) and updates for Play Store

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-android#1770]
We will need to submit an update to the Android app for release on Sep. 6
Make sure the app can be released and has the new logo (due on Friday, 12.Sep.)

- Replace app logo with new version
- Remove Gnosis in all visible places.
- Update targetSdkVerison to 32
- Update compileSdkVersion to 32
- Update Gradle to newest relase
- Update Gradle plugin to recommended version
- Update launcher icons and logo in splash screen

- Update Buildkite to also have all the changes to the build environment, that are not within the git repo

https://user-images.githubusercontent.com/246473/185446619-d64ee1e6-6f15-4904-b493-200a637f28c6.mp4

**Comment by TanyaEfremova** [comment]
Here is the logo package! [https://app.zenhub.com/files/96440096/34305b44-ce17-49f7-93dc-63ac736e6822/download](https://app.zenhub.com/files/96440096/34305b44-ce17-49f7-93dc-63ac736e6822/download)

**Comment by biafra23** [comment]
@TanyaEfremova This seems to be the Apple/iOS version of the Logo. Are you able to create the same for Android?

**Comment by biafra23** [comment]
@TanyaEfremova Also: We need an vector image of the logo for newer devices.

**Comment by biafra23** [comment]
At the moment the logo in the splash screen is a vectro log with a transparent background. If I replace this with the logo from the zip file it most like will look horrible.

**Comment by TanyaEfremova** [comment]
Please, ignore the package above. Try this one: [https://app.zenhub.com/files/96440096/4c42255c-4105-4e00-9e72-0ecd45690850/download](https://app.zenhub.com/files/96440096/4c42255c-4105-4e00-9e72-0ecd45690850/download)

Here is the SVG for the splash screen. ![Black.svg](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/607ece1c-3c2b-422d-bde0-1c7306ab5776)

**Comment by TanyaEfremova** [comment]
Due to the discussion[ in this thread](https://5afe.slack.com/archives/C03CT23SU1Z/p1661345009270079), we will need to change the launcher icons temporarily.

Please, see [here](https://www.figma.com/file/rqIpWH6iJabWWTaMatlGqA/Android-UI-Kit-%E2%80%94-Rebrand?node-id=439%3A1983) - we will use the B&W version for the production version.

No new icons are necessary, just a replacement for now.

**Comment by TanyaEfremova** [comment]
See updated [splash screen](https://www.figma.com/file/rqIpWH6iJabWWTaMatlGqA/Android-UI-Kit-%E2%80%94-Rebrand?node-id=422%3A2382)

New slogan: The most trusted platform to manage digital assets.

Splash logo attached ![White.svg](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/e126ea38-4c00-4d2f-8884-c9a3eeb44010)

**Comment by biafra23** [comment]
@TanyaEfremova The slogan is an image on Android.

**Comment by TanyaEfremova** [comment]
See app store screenshots: [Design](https://www.figma.com/file/NIPwfjfjh0xvfn6u4w2QXd/App-Store-Screens?node-id=601%3A70)

**Comment by liliya-soroka** [comment]
Verified 
app version 3.4.0 -3496rc
