### ISSUE TITLE
[MiniRebrand] What's New screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-android#1773]
- Title: “We have changed!”  
- Text: "Gnosis Safe rebranded to Safe. Following a successful spin-off vote from Gnosis in GIP-29, we are rebranding to Safe. Now and over the coming time, you will see a new look and a better visual experience to your ever secure Gnosis Safe that you love."

icon: TBD

**Comment by TanyaEfremova** [comment]
Please, see icons [here](https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-new?node-id=407%3A559)

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3496rc
