### ISSUE TITLE
Play Store entry update (text & images)

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-android#1774]
Current entry:

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/d46d2040-70f5-4b87-85c7-ca5b58dfb34a
)

AFAICT we need the following: 
- Change the app name `Gnosis Safe Multisig` -> `Safe`
- new Logo (green)
- Revise the description and remove Gnosis from it
- New screens?
- Do we update the Developer (GnosisPM)? If so, to what?

**Comment by TanyaEfremova** [comment]
See app store screenshots: [Design](https://www.figma.com/file/S0z978hWxtCUbnwoiYAqvB/Google-Store?node-id=0%3A1)

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0
