### ISSUE TITLE
[Send funds] Total balance panel

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-android#1780]
[ ] Add panel above cons and collectibles tab for displaying total balance
[ ] Remove total balance item from the coins list

![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/4cdb9d8e-2dc5-4f62-a984-9021518bb8b3)

[ ] show safe info screen when clicking `Receive`
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/19b44fa1-9df4-4657-a0d9-3f78e2eabaac)

design: https://www.figma.com/file/FH6kqYzmW99z20B6h6Sx5W/Initiate-assets-transer?node-id=701%3A2657

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3576
