### ISSUE TITLE
[Send funds] Select asset screen

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-android#1781]
Add screen for selecting an asset for an asset transfer
[ ] Accessible through click on the `Send` button from total balance panel on the assets screen
[ ] Assets can be filtered by name and symbol
[ ] Show placeholder for an empty list (when no asset was found for a search term)

![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/61c0897b-0d65-440f-a833-8ed639b9c06f
)

placeholder for an empty result
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/c9e25107-5309-49bc-9d94-16da3d3b42b3)

design: https://www.figma.com/file/FH6kqYzmW99z20B6h6Sx5W/Initiate-assets-transer?node-id=701%3A2630

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3576
