### ISSUE TITLE
[Send funds] Edit advanced parameters

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-android#1783]
Add screen for editing advanced parameters:

- Safe nonce
- SafeTxGas (not always present. Only for safes < 1.3.0 )

When parameter labels are clicked show info tooltip containing parameter description.
Tooltip will not be having an arrow to reduce implementation effort (taking tooltip from legacy app).

`How do I configure these parameters manually` link leads to `https://help.gnosis-safe.io/en/articles/4738445-advanced-transaction-parameters`

Validation logic same as in ios.

![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/9577fc5a-190c-455d-a022-7acbba220c8b
)

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3652
