### ISSUE TITLE
[Send funds] Send asset screen

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-android#1784]
Screen content: 

 - Sender name address view (current safe, copy address to clipboard when clicked)
 - Address input field for recipient
 - Amount input field

Address input possibilities same as for entering safe address (TODO: extract to separate task)
- Copy from clipboard
- ENS 
- Unstoppable domains (if available)
- QR code

Address book and prefixes are not available.

When clicking `Send max` enter max available amount into amount field

Amount formatting rules apply for amounts on the screen
https://github.com/5afe/safe/wiki/How-to-format-amounts

ios not showing symbol abbreviation in the right part of the input field because of some long token symbols. Same should apply for android version.

Same logic for amount checking as on ios (amount greater than zero and not bigger than max amount)
Show validation errors

`Review` button is disabled till valid non-zero amount is entered
Also REVIEW action is available in the toolbar (in the right cornter; same enabled/disabled logic)

![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/89ad865b-864c-4e21-b150-b67c40d770c6
)

**Comment by liliya-soroka** [comment]
"Also REVIEW action is available in the toolbar (in the right cornter; same enabled/disabled logic)" moved to https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-android/1849

**Comment by liliya-soroka** [comment]
verified
app version 3.5.0 -3676
