### ISSUE TITLE
[Send funds] Review screen

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-android#1785]
Add review screen for reviewing send funds transaction.

Screen content:
TBD

<img src="https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/70fccd41-4ae1-47a6-9109-21327ce17fbe" width=300 />

<img src="https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/47eee301-53ff-43b0-b658-fa1b881ce3f4" width=300 />

## Notes
- Do not implement fiat amount: conversion can be outdated + increases the scope
- Advanced parameters should be editable in a separate screen. Safe Tx Gas is editable depending on the contract version.
- Do not implement the address prefix for addresses.

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0-3652
