### ISSUE TITLE
[SendFunds] Send Funds transaction on Android

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-android#1788]
# Problem Statement
[Notion](https://www.notion.so/gnosis-safe/Send-funds-transaction-on-Android-7b58646b8bd84bc4bed76b5e4d763088)

> Most of the Android users in the past user interviews are complaining about lack of functionality, i.e. ability to execute transactions or send funds. What this leads to is that people can confirm a transaction on the mobile device, but have to wait until they’re on the laptop to execute the transaction or to create a transaction. 

# Solution
Implement send funds transaction creation for Ethereum, and Goerli

**Overview**

- Implement send funds transaction creation with imported or generated key
- Adapt transaction UI designs to Android platform look and feel
- “What’s new” to let users know of a new functionality

**Rough Scoping** 

- v1 includes: Ethereum, Goerli + only imported/generated keys to control the size of the work.
- Measuring the volume and fees generated on mobile from send funds transfer transactions.

**Risk(s), Key Trade Offs & Decisions**

- Need to update library dependencies on Android, preparation for Android 13

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 -3691rc
only minor issues are left
