### ISSUE TITLE
[Send funds] What's new screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-android#1789]
- [x] Title: `Asset transfers have arrived!`
- [x] Description: `Now you can send assets from your Safe on Android from the Assets screen. This will create a new transaction which needs to be signed and executed by other owners.`
- [x] Icon TBD

**Comment by DmitryBespalov** [comment]
@elgatovital I've added title and description

**Comment by liliya-soroka** [comment]
Verified
app version 3.5.0-3610rc
