### ISSUE TITLE
[Android] Light theme owner key icons on dark theme

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-android#1790]
**Describe the bug**
When adding an owner key via any of the available options (import, create, connect) while using the dark theme of the app, the icons for the tutorials shown on screen belong to the light version theme instead of the dark one.

**To Reproduce**
The issue is reproducible on v3.3.1 (3475) of the app
-Go to Settings -> Add owner keys -> Choose any (and eventually all) of the options (note that the icon for when no owner keys have been added has the incorrect theme as well).

**Actual behaviour**
Light theme icons are shown

**Expected behaviour**
Dark theme icons are shown

**Screenshots**
![IMG_0677.jpeg](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/1e47f00d-f04a-40f4-bd1b-52364e6d56d5)
vs

![IMG_0678.jpeg](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/6a7e6cff-bc2a-4197-81cd-f91c9cb06dc4)

**Comment by liliya-soroka** [comment]
Verified
app version 3.5.0-3676
