### ISSUE TITLE
[Android] 'No safe loaded' header clickable after removing last safe

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-android#1793]
**Describe the bug**
After all safes are removed from the app, the 'No safe loaded' header is still clickable when it shouldn't

**To Reproduce**
Issue is reproducible on 3.4.0 (3496) RC
1. Install the app
2. Add at least one safe
3. Remove it from safe settings
4. Click the 'No safe loaded' header

**Current behavior**
![Screenshot_2022-09-01-10-58-04-60_26ff3db7d38c242905746415e9d6f1eb.jpg](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/2670c7ff-16f7-4d22-809c-e020639aa75d)

**Expected behavior**
Nothing should pop up on screen

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 -3691rc
