### ISSUE TITLE
[android] Can not connect Ledger nano X on Google Pixel 3a/5/6

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-android#1795]
**Describe the bug**
Can not connect Ledger nano X on android

**To Reproduce**
1. Install the app
2. add safe and try to add Ledger Nano X as a key
3. approve Location permissions
Current result: The app is closed

4. restart the app 
5. start the connect ledger nano x flow
Current result: Issue with connection screen is displayed all the time

**Expected behavior**
It should be possible to connect Ledger Nano X on Google Pixel

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/2153f49f-15fc-48e9-91b6-50f512eea595)

**Smartphone (please complete the following information):**
 - Device: google Pixel  5
 - Android Version: android 12
 - App Version 3.4.0

**Environment**
prod
**Additional context**

**Comment by biafra23** [comment]
This seems to be device specific. When this is to be tackled, can we have access to a Pixel 5, please?

**Comment by bogdoslavik** [comment]
Same for Galaxy S21 5G. After app rebranding it does not see my Ledger Nano X. Tried everything: reboot, safe removal, ledger unpair and pair again. Ledger Live works well.
Can provide logs / data you needs.
Please fix.

**Comment by javalasers** [comment]
Had the same issue with a pixel 6. Just upgraded to pixel 7 and have the same issue on the 7 as well. The pixel 6 worked for a time, but stopped working within the last few months. (Sorry I don't have a precise time).

**Comment by biafra23** [comment]
Works on Android 8 / Nexus 5x
Devices not visible on Pixel 3a (Android 12)
Device visible but cannot be connected on Fairphone 5 with Anddroid 11
Same behaviour on current version in Play store  (3.4.0 and 3.3.1) .

**Comment by biafra23** [comment]
On the Pixel 3a the Nanos shows up (but retrieving keys fails) on build from sha-1 433ee7d9e62f1bb59f96740d57d9f6e7aedbbe96

**Comment by markusbkoch** [comment]
Same issue, Pixel 7 Pro, Android 13

**Comment by gpersoon** [comment]
I just checked the log via `adb logcat` and see the following:
```
11-24 16:47:49.190 20062 20062 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=39816136, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {io.gnosis.safe/io.gnosis.safe.ui.StartActivity}: java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@eacdceeb: GattService registerScanner
11-24 16:47:49.190 20062 20062 E AndroidRuntime: Caused by: java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@eacdceeb: GattService registerScanner
```

So I guess the `android.permission.BLUETOOTH_SCAN` permission is missing.
This is required in android 12, see [bluetooth permissions](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#declare-android12-or-higher)

The [AndroidManifest.xml](https://github.com/safe-global/safe-android/blob/master/app/src/main/AndroidManifest.xml) doesn't seem to have this.

**Comment by liliya-soroka** [comment]
Update: 
No crash, and it's possible to connect/pair devices. 
But there is one issue with the list of addresses: manual page refreshing is required to select the address after pairing. 


![Image](https://user-images.githubusercontent.com/338622/218786905-6cb33668-43a2-4545-847b-618366074909.png)

**Comment by biafra23** [comment]
The remaining problem is as follows: 
When connecting to the Ledger for the first time a BLE pairing is initiated. Somehow this interferes with the loading of the addresses. The screen above is shown. The solution is either to pull to refresh or go back and connect again. 

We should make a ticket for sthi bug and tackle it later.

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.2-3813rc
For the comment above a new ticket will be created
