### ISSUE TITLE
[Rebrand] Colors transition (Backgrounds, gradients)

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-android#1804]
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/aa72b26e-46a4-4c06-85b1-50e095739c1f)

[Color tables](https://www.figma.com/file/rqIpWH6iJabWWTaMatlGqA/Android-UI-Library?node-id=0%3A1) (Figma)

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3618
