### ISSUE TITLE
[Rebrand] Visuals and illustrations, logo

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-android#1805]
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/eb321255-9e6b-455c-bd01-e8ffe7a2addf)
 
[Illustrations](https://www.figma.com/file/rqIpWH6iJabWWTaMatlGqA/Android-UI-Library?node-id=621%3A6384) (Figma)
[Logo (Launcher icons)](https://www.figma.com/file/rqIpWH6iJabWWTaMatlGqA/Android-UI-Library?node-id=415%3A1816) (Figma)

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3576
