### ISSUE TITLE
[Rebrand] Update styles for text

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-android#1815]
See Figma: https://www.figma.com/file/rqIpWH6iJabWWTaMatlGqA/Android-UI-Library?node-id=407%3A2125

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/e7e02a3d-d37a-45ce-9b13-c1e9c6ee6136)

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3618
