### ISSUE TITLE
[rebrand] load safe flow issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-android#1820]
- [x] Choose network
implementation:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/16bfd2ab-eccb-4e05-9873-45dc9d594cb8)(safe was created.... text color) - design - https://www.figma.com/file/xxCMH9tgwOpaQZ4Fzhjnf2/Android-Master-File?node-id=1228%3A30020

- [x]  Enter safe address screen issue
- Enter safe address text has wrong color
- Don't have a Safe ... contains two colors : text has Light/Labels/labelSecondary#636669 and link with link icon have Light/Labels/labelPrimary#121312 ( please add it for the links all over the app)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/818c345f-4cef-4893-821d-1cdb56f4d028)
Design - https://www.figma.com/file/xxCMH9tgwOpaQZ4Fzhjnf2/Android-Master-File?node-id=121%3A21829

- [x] address is found
- is page title "Primary/Subtitle" ?
- wrong color for "enter your safe multisig"

- [x] choose safe name
- "Choose a name for the safe..." has wrong color - It should be Light/Labels/labelSecondary
#636669
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/fc8b9c9f-3b2d-42f7-8173-d601ac3431c0)

![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/479828fe-950c-485e-a63b-d8165583bc26)

**Device & App version**
 - Device/OS: pixel
 - App version: 3.4.0-3576
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
@biafra23 , I have unmarked 2 checkboxes as they are not fixed according to the design

app version 3.4.0 -3618

**Comment by biafra23** [comment]
expected | actual 
-------- | ------- 
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/f500fb24-8f1c-433c-976c-4c1041de50e6) | ![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/b01161a7-893f-4bbb-863a-4e77bbbf0c02)

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3624
