### ISSUE TITLE
[rebrand][Txs list issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-android#1821]
- [x] a few txs with the same nonce
- Learn more link and link icon should have Light/Foundation/primary#121312 color
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/0e42dbd6-cfc7-4a54-a851-7991bb8ce693)

- [x] confirmations when the tx is fully signed have Base/success#00B460 and Light/Components/icon#A1A3A7 when more confirmations are required
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7b576774-bab7-4593-82e6-3738ab114041) - design https://www.figma.com/file/xxCMH9tgwOpaQZ4Fzhjnf2/Android-Master-File?node-id=121%3A35729

- [x] wrong text color. Expected: Light/Labels/labelSecondary
#636669 in light theme and Dark/Labels/labelSecondary
#A1A3A7 in the dark
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8e79d2d7-2d6a-4ec0-a8b9-320da52bd8aa)

- Device:
- Android OS version:
- Safe app version:

**Comment by biafra23** [comment]
@liliya-soroka 

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/3539303f-7aec-48fb-8532-f83a7a253bbd)

The confirmations are #00B460 (success/dark_green) in this screenshot.

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3618
