### ISSUE TITLE
Disable SSL pinning temporarily

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-android#1828]
SSL certificates are about to change several times for our safe.global website, so DevOps (Raul) asked to temporarily switch off the SSL pinning for new service URLs after migration.

Please disable / do not configure SSL pinning for the new safe.global domains.

We'll need to enable it when the certificates are configured for sure.

**Comment by biafra23** [comment]
Can't we pin on something higher up the certificate chain? So any cert is accepted that is signed by the organization? That way we do not have to renew the the pinning every time a new certificate is used.

**Comment by liliya-soroka** [comment]
Verified
