### ISSUE TITLE
What's New screen for rebrand

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-android#1835]
Title: New look!

Safe is following up with a new look. We have updated the color palette in the app, including dark mode.

Design: please take the icon from the minimal rebranding [Figma](https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-new?node-id=407%3A559)

**Comment by liliya-soroka** [comment]
Verified
app version 3.5.0 -3638rc
