### ISSUE TITLE
[Android] [send funds]Open Add key on "send" if no added owner key

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-android#1839]
**Bug description**
Open Add key on "send" if no added owner key
**Steps To Reproduce**
1.There is no added owner key
2. click send funds
Current result: send funds flow is started

**Expected Result** Add owner key flow should be started
Check on ios 
**Device & App version**
 - Device/OS: android
 - App version: 3.4.0 -3652
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by elgatovital** [comment]
fyi: https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-android/1845

**Comment by liliya-soroka** [comment]
Verified taking into account the comment above
app version  3.5.0 -3676
