### ISSUE TITLE
[Android] Deprecate soon for versions with v1 collectibles endpoint

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-android#1861]
Epic: https://www.notion.so/gnosis-safe/iOS-Android-Collectibles-v2-release-and-v1-deprecation-8292f77897a34f038aff31b53da17003

Set `deprecatedSoon` remote config value for versions with collectibles v1 endpoint

**Comment by liliya-soroka** [comment]
@elgatovital , I see the"deprecated soon" screen in the internal app, but no screen for the prod app 
tested version 3.6.0-3691rc

**Comment by liliya-soroka** [comment]
verified
