### ISSUE TITLE
Create rejection transaction disabled when returning from key selection

### ISSUE THREAD

**Issue by rmeissner** [safe-global/safe-android#1873]
**Describe the bug**
The button in the rejection screen to create a rejection transaction is disabled when returning from key selection.

**To Reproduce**
1. Start "Reject flow" (click "Reject" on any transaction)
2. Click on 'Reject Transaction'
3. Go Back
4. See  'Reject Transaction' is disabled

**Expected behavior**
 'Reject Transaction' button should be enabled.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - Android Version: 13
 - App Version 3.2.0-3401

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.1-3787rc
