### ISSUE TITLE
Can not add safe or recipient on Send funds using ENS name ( prod app)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-android#1879]
**Describe the bug**
Can not add safe using ENS name ( prod app)

**To Reproduce**
1. Clean install prod app
2. Try to add safe using ENS name ( safetest2.eth for Goerli)
Current result: Error message is displayed and the safe is not defined. I don't have such problem in the internal app

**Expected behavior**
Make sure that it's possible to add safe using ENS name

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - Android Version:android 13
 - App Version 3.6.1-3787rc

**Environment**
prod
**Additional context**

**Comment by elgatovital** [comment]
@liliya-soroka could you check if there was a leading white space when you were entering safetest2.eth? `safetest2.eth` works for me, but ` safetest2.eth` currently is handled as an invalid address. 
<img width="266" alt="image" src="https://user-images.githubusercontent.com/17750984/210802742-0a269811-de23-418f-bfb4-1b9097d55c5c.png">
Is this the same error you were getting?

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.1-3801rc
