### ISSUE TITLE
[Android] Change URLs of discord invite links in help center

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-android#1880]
As a user 
I want to access the authentic Safe Discord and not a fraudulent one
so that I will not be a victim of a phishing attack 

**Background**

Currently we use invalid discord invite links in our help center. We need to make sure to replace all URLs that point to Discord with links that go through our domains (e.g. https://chat.safe.global/. This is a security issue as it is possible to claim invalid link as vanity URLs which then can be used for phishing the user to a malicious discord server. 

**What needs to be done**

Change the current links in the help center to https://chat.safe.global/
(User flow: open app --> click "Settings" button --> click "Help Center" --> click "Discord)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.1-3807
