### ISSUE TITLE
[Android] Change source for Terms of use, Privacy policy, and Licenses in the About Safe section

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-android#1882]
**Background**

On Android we are currently using http://gnosis-safe.io/ to open privacy policy , terms of use, licenses (example https://gnosis-safe.io/licenses/). On web https://safe.global/licenses/ is used. We need to keep the links updated and should use the safe.global... links 

**What needs to be done**

Replace

for Terms and Conditions: https://gnosis-safe.io/terms with https://safe.global/terms
for Privacy policy: https://gnosis-safe.io/privacy with https://safe.global/privacy
for Licenses: https://gnosis-safe.io/licenses with https://safe.global/licenses

in the About Safe section of the application

**Comment by biafra23** [comment]
@liliya-soroka The help center link stays at https://help.gnosis-safe.io for now?

**Comment by liliya-soroka** [comment]
yes, I think it's still gnosis-safe.io for the help center

**Comment by liliya-soroka** [comment]
Verified 3.6.1-3797rc
