### ISSUE TITLE
Cannot connect Ledger Nano X for signing

### ISSUE THREAD

**Issue by tschubotz** [safe-global/safe-android#1883]
**Describe the bug**
Cannot connect Ledger Nano X for signing

**To Reproduce**
1. Install vanilla Safe app
2. Go to app Settings
3. Tap "owner keys"
4. Tap add (top right)
5. Tap “connect ledger X”
6. Tap “next”
7. App prompts for location access -> tap "allow while using app"

💥  app crashes

9. Reopen app
10. Repeat steps 2. - 6. 
11. Unlock ledger and open Ethereum app
12. Wait
13. Pull to refresh
14. Wait

😢  nothing happens, ledger nano X doesn't show up

**Expected behavior**
I can view and connect my ledger nano x and use it for signing

**Screenshots**
 - 

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Android Version: Android 12
 - App Version: Tried both with `3.6.0` and `3.6.1-3787rc`

**Environment**
- Prod mainnet

**Additional context**
- I removed the pairing between ledger and my phone via system bluetooth settings
- I resetted pairings on the ledger
- I restarted my phone
- tried with 2 ledgers:
  - Ledger A: Ethereum app version: 1.10.1, Firmware: 2.0.2
  - Ledger B: Eth app version: 1.9.19, Firmware: 2.0.2
 - [Slack convo here.](https://5afe.slack.com/archives/C03CT23SU1Z/p1673037481854779)

**Comment by liliya-soroka** [comment]
Known issue  - https://github.com/safe-global/safe-android/issues/1795
