### ISSUE TITLE
[Android] Rebrand: Reflecting change to Safe{Wallet} on our interface

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-android#1904]
As Safe 
we want our users to see the change to Safe{Wallet} in all our interfaces
so that everyone is aware of the rebrand

**What needs to be done**
One need to do a global search for "Safe"/"safe" go through all instances and changing them as specified below.
The usage of Safe{Wallet}, Safe Account and Safe is context sensitive, i.e.
- We need to replace the logos with Safe{Wallet} logo as specified in the comment below
- If we are referring to the whole project we need to use _Safe_
- If we are referring to a specific Safe account we need to use Safe Account
- If we are to the Safe interface we need to use Safe{Wallet}

**If in doubt**
Tanya is the go-to person

**Acceptance criteria**
Logo change and text change

**For reference**
- Web implementation https://github.com/safe-global/safe-wallet-web/pull/1884/files
- Safe brand map https://docs.google.com/presentation/d/1c7IHqREWFvKtc5ngV1uZBi9eDp2ocHld0fWLBkTyQPs/edit#slide=id.g21ca932d5f6_0_0

**Comment by liliya-soroka** [comment]
Verified
app version 3.20.0(1762)
