### ISSUE TITLE
[Anroid] Intercom: workspace migration + help desk article links

### ISSUE THREAD

**Issue by med3000** [safe-global/safe-android#1906]
# Description

Safe is moving Intercom workspaces from US to EU hosted.

# What To Do

- Update app ID (reach out to admin in Slack) and any article links with new workspace config
- Update link to help desk articles as documented in this table https://docs.google.com/spreadsheets/d/153sBQbMDzvW-OCXWl0yzDZQWCkqzCVc2hjYMsqIVXcQ/edit#gid=0

# Acceptance criteria
- App ID updated
- New links in place

[Technical steps to do]

install: https://developers.intercom.com/installing-intercom/docs/intercom-for-android

hosting region: to be updated to EU https://developers.intercom.com/installing-intercom/docs/data-hosting-region-configuration-android

**Comment by liliya-soroka** [comment]
verified
app version 3.6.4
