### ISSUE TITLE
[Keystone integration] The error should be shown if a user is trying to scan incorrect QR code

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-android#1926]
**Describe the bug**
The error should be shown if a user is trying to scan an incorrect QR code

**To Reproduce**
1. Try to connect keystone key using incorrect QR code or try to sign tx using incorrect QR code 
Current result: Nothing happens

**Expected behavior**
The error should be shown to the user that wrong QR code is used

**Smartphone (please complete the following information):**
 - Device: pixel 6
 - Android Version: Android 13
 - App Version keystone_integration.apk

**Environment**
staging
**Additional context**
https://github.com/safe-global/safe-android/pull/1911

**Comment by zhiying-fan** [comment]
This is fixed, please have a look again.

**Comment by liliya-soroka** [comment]
Verified
