### ISSUE TITLE
[android] unknown tx type (twap)

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-android#2046]
Edit order types according to the changed CGW types: https://github.com/safe-global/safe-gateway-typescript-sdk/commit/99fce976c8d231fad94ef27c3b4423b3a2e4abe9

**Comment by liliya-soroka** [comment]
Reopened:
TWAP and Swap order settlement are not displayed on UI in Queued and History - sep:0x2a73e61bd15b25B6958b4DA3bfc759ca4db249b9 on staging
