### ISSUE TITLE
[android] recognize limit order type

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-android#2049]
Recognize order type 'limit' order. Distinguished by the `fullAppData.metadata.orderClass.orderClass` property value `limit`.

**Comment by liliya-soroka** [comment]
Moved back 
@DmitryBespalov , for some reason Limit order is not recognised in the Queued list but recognized in the history 
safe = sep:0x2a73e61bd15b25B6958b4DA3bfc759ca4db249b9 on staging 
tx nonce =357
